name: Build and Push

on:
  workflow_dispatch:
    branches: ["main"]
    inputs:
      dockerNamespace:
        description: 'Docker Namespace'
        default: 'swaggerapi'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_NS }}/swagger-oss-services-fe:latest
    env:
      DOCKER_NS: ${{ github.event.inputs.dockerNamespace }}
